import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Aperture } from "lucide-react";
import { SelectProject } from "@/components/select-project";
import { getProjects } from "@/actions/projects";
import { DialogProvider } from "@/components/dialog-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const projects = await getProjects();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <DialogProvider>
          <header className="flex border-b h-14 shrink-0">
            <div className="flex w-64 px-6 items-center">
              <h1 className="font-bold flex gap-2">
                <Aperture />
                <span>Admin Panel</span>
              </h1>
            </div>
            <div className="flex items-center">
              <SelectProject projects={projects} />
            </div>
          </header>
          {children}
        </DialogProvider>
      </body>
    </html>
  );
}
