import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Aperture } from "lucide-react";
import { SelectProject } from "@/components/select-project";
import { getProjects } from "@/actions/projects";
import { DialogProvider } from "@/components/dialog-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { getServerSession } from "@/lib/auth-session";
import { UserMenu } from "@/components/user-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const projects = session ? await getProjects() : [];

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DialogProvider>
            {session ? (
              <header className="flex border-b h-14 shrink-0">
                <div className="flex w-64 px-6 items-center">
                  <h1 className="font-bold flex gap-2">
                    <Aperture />
                    <span>Admin Panel</span>
                  </h1>
                </div>
                <div className="flex items-center flex-1">
                  <SelectProject projects={projects} />
                </div>
                <div className="flex items-center gap-2 px-4">
                  <ThemeToggle />
                  <UserMenu user={session.user} />
                </div>
              </header>
            ) : null}
            {children}
          </DialogProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
